2020-08-18 12:22:40,839 - Config - config_parser.py->_read_file[line:83] - ERROR - file:config.aini dosen't exist 
2020-08-18 12:22:40,839 - test - test.py-><module>[line:15] - INFO - hello 
